export const UPDATE_METADATA = "UPDATE_METADATA";
export const CREATE_METADATA = "CREATE_METADATA";
export const CREATE_MASTER = "CREATE_MASTER";
export const UPDATE_MASTER = "UPDATE_MASTER";
export const DELETE_MASTER = "DELETE_MASTER";
export const RETRIEVE_MASTERS = "RETRIEVE_MASTERS";
export const DELETE_ALL_MASTERS = "DELETE_ALL_MASTERS";
export const FETCH_MASTER = "FETCH_MASTER";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_SELECT_METADATA = "UPDATE_SELECT_METADATA";
export const UPDATE_SELECTED_DROPDOWN = "UPDATE_SELECTED_DROPDOWN";
export const UPDATE_SELECTED_DROPDOWN_DYNA = "UPDATE_SELECTED_DROPDOWN_DYNA";
export const GET_SELECTED_ITEM = "GET_SELECTED_ITEM"
export const GET_NEXT_ID = "GET_NEXT_ID"
export const UPDATE_AUTHDATA = "UPDATE_AUTHDATA"
export const DROPDOWN_INIT_DYNA = "DROPDOWN_INIT_DYNA"
export const LOCAL_GET_NEXT_ID = "LOCAL_GET_NEXT_ID"
export const SET_IS_LOADING = "SET_IS_LOADING"


