export const title = {
    Company_Information: "companyinfo",
    Opening_Information: "openinginfo",
    Employee_Master: "employeemaster",
    Account_Master: "accountmaster",
    Item_Master: "itemmaster",
    Operation_Master: "operationmaster",
    Machine_Master: "machinemaster",
    Workstation_Master: "workstationmaster",
    General_Work_List: "genworklist",
    Payment_Mode: "paymentmode",
    Work_Order: "workorder",
    Daily_Work_Report: "dailyreport",
    Job_Work_Order: "jobworkorder",
    Job_Work_Receipt: "jobworkreceipt",
    Sale_Challan: "salechallan",
    Payment: "payment",
    Rejection: "rejection",
    Work_Book: "workbook",
    Work_Order_Register: "workorderreg",
    Pay_Slip: "payslip",
    Salary_Ledger: "salaryledger",
    Production_Ledger: "prodledger",
    Account_Ledger: "accountledger",
    // Item_Master_ListPage:"itemmaster/item?param=1"
};
