export const APP_NAME = "MACHINEX";

export const APP_DATA = {
  EMPLOYEEE_MASTER: {
    EMPLOYEE_DETAILS: [
      "Employee ID",
      "Joining Date",
      "Release Date",
      "First Name",
      "Middle Name",
      "Last Name",
      "Gender",
      "DOB",
      "Mobile Number",
      "Aadhar Number",
      "Email",
    ],
    BANK_DETAILS: ["Account Number", "IFSC Code", "Bank Name"],
    USER_DETAILS: ["Username", "Password", "Access Category"],
    SALARY_DETAILS: [
      "Date",
      "Designation",
      "Salary per day",
      "Overtime Ratio",
      "Earning Ratio",
      "incentive Ratio",
    ],
  },
  COMPANY_INFORMATION: [
    "Name",
    "Address",
    "Pin Code",
    "State",
    "Country",
    "Contact",
    "Email",
  ],
  ITEM_MATER: {
    DRAWING_DETAILS: [
      "Drawing Number",
      "Drawing Description",
      "Job Dimensions",
      "Material Handling Charges",
    ],
    OPERATION_MASTER: [
      "Caunter",
      "Caunter Drilling for Tapping",
      "Tapping",
      "Rough Turning",
      "Finish Turning",
      "Thrading",
      "Circlip Groove",
      "Chamfers & Undercuts",
    ],
    OPERATION_FORM: [
      "Opn. No.",
      "Operation",
      "Opn. Description",
      "Opn. Details",
      "Time in Min,	Cost",
    ],
  },

  DAILY_WORK_REPORT: {
    WORKER_DETAILS: [
      "Report Number",
      "Worker Number",
      "Worker Name",
      "Date",
      "Check In Time",
      "Check Out Time",
    ],
    DAILY_WORK_REPORT_FORM: [
      "Sr. No.",
      "Macine No.",
      "Drawing No.",
      "Operation",
      "Opn. Details",
      "Qty.",
      "Time",
      "Earning Cost",
    ],
    MACHINE_MASTER: [
      "Sr. No.",
      "Machine Name",
      "Macine Specification",
      "Operation",
      "Machine / Hrs Rate",
    ],
    GENERAL_WORK_LIST: ["No Current", "No Work", "Machine Difect"],
  },
  REJECTION_REPORTS: {
    INFO: ["Report Number", "Date", "Account Name"],
    REJECTION_FORM: [
      "Sr. No.",
      "Drawing No.",
      "Qty.",
      "Material Cost",
      "Rejection Details",
    ],
  },
  WORK_ORDER: {
    WORK_ORDER_DETAIL: ["Work Order Number", "Date", "Customer Name"],
    WORK_ORDER_FORM: [
      "Sr. No.",
      "PO No. / Item No.",
      "Drawing No.",
      "Qty",
      "Rate",
      "Work Details",
      "Remark",
    ],
  },
  ACCOUNT_MASTER: {
    ACCOUNT_MASTER_FORM: ["Sr. No.", "Account Name", "Address"],
  },
  JOB_WORK_ORDER: {
    JOB_ORDER_DETAIL: ["Job-Work Order No.", "Date", "Vendor Name:"],
    JOB_ORDER_FORM: [
      "Sr. No.",
      "Drawing No.",
      "Qty",
      "Delivery Date",
      "Work Details",
      "Rate",
      "Total Cost",
    ],
  },
  JOB_WORK_RECEIPT: {
    JOB_ORDER_DETAIL: ["Inward No.", "Date", "Vendor Name:"],
    JOB_ORDER_FORM: [
      "Sr. No.",
      "Ref. Order No.",
      "Drawing No.",
      "Qty",
      "Rate",
      "Total Cost",
      "Remark",
    ],
  },
  PAYMENT_DETAILS: {
    PAYMENT_INFO: [],
    PAYMENT_DETAILS_FORM: [
      "Sr. No.",
      "Account Name",
      "Debit (DR)",
      "Credit (CR)",
      "Payment Mode",
    ],
    PAYMENT_MASTER: {
      S_N: "Sr. No.",
      MODE_OF_PAYMENT: [
        "Bank Transfer",
        "G-Pay Transfer",
        "Phone-Pe Transfer",
        "Cash",
      ],
    },
  },

  MAIN_GROUP: {
    OPERATIONS: {
      TURNING: {
        CAUNTER: ["BS5 Caunter", "BS4 Caunter"],
        DRILLING: [
          "M10 Drilling",
          "M12 Drilling",
          "M16 Drilling",
          "M20 Drilling",
        ],
        ROUGH_TURNING: ["Rough -I", "Rough -II"],
        FINISH_TURNING: ["Finish - I", "Finish - II"],
        UCUT_CHAMFERS: ["All Undercuts", "All Chamfers"],
      },
      GRINDING: {
        ROUGH_GRIDING: ["Side Rough Grinding -I", "Side Rough Grinding - II"],
        FINISH_GRINDING: [
          "Side Finish Grinding - I",
          "Side Finish Grinding - II",
          "Coupling Grinding",
        ],
      },
      KEYWAY: ["6-10mm Keyway", "12-16mm Keyway"],
      MANUAL: ["Inspection", "Packing", "Other"],
    },
  },

  FORMDATA: {
    DAILY_WORK_REPORT_FORM: {
      SECTIONS: {
        SECTION_1: "General Work Details",
        SECTION_2: "Work Hours",
        SECTION_3: "Work Details",
      },
      WORK_DETAILS: [
        {
          KEY: 1,
          NAME: "drawingNumber",
          LABEL: "Drawing Number",
          ORDER: 1,
          SELECT: true,
          INPUT: false,
        },
        {
          KEY: 2,
          NAME: "operationCode",
          LABEL: "Select Operation",
          ORDER: 1,
          SELECT: true,
          INPUT: false,
        },
        {
          KEY: 3,
          NAME: "operationDescription",
          LABEL: "Operation Description",
          ORDER: 1,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 4,
          NAME: "machineID",
          LABEL: "Select Machine",
          ORDER: 1,
          SELECT: true,
          INPUT: false,
        },
        {
          KEY: 5,
          NAME: "machineDescription",
          LABEL: "Machine Description",
          ORDER: 1,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 6,
          NAME: "quantity",
          LABEL: "Quantity",
          ORDER: 1,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 7,
          NAME: "totalPrice",
          LABEL: "Cost",
          ORDER: 1,
          SELECT: false,
          INPUT: true,
        },
      ],
      WORK_HOUR: [
        {
          KEY: 1,
          NAME: "Date",
          LABEL: "Date",
          ORDER: 1,
          SELECT: false,
          INPUT: false,
          DATE: true,
        },
        {
          KEY: 2,
          NAME: "checkInTime",
          LABEL: "Check-In Time : ",
          ORDER: 2,
          SELECT: true,
          INPUT: false,
        },
        {
          KEY: 3,
          NAME: "checkOutTime",
          LABEL: "Check-Out Time",
          ORDER: 3,
          SELECT: true,
          INPUT: false,
        },
        {
          KEY: 4,
          NAME: "reportNumber",
          LABEL: "Report Number",
          ORDER: 4,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 5,
          NAME: "workerNumber",
          LABEL: "Worker Number",
          ORDER: 5,
          SELECT: true,
          INPUT: false,
        },
        {
          KEY: 6,
          NAME: "workerName",
          LABEL: "Worker Name",
          ORDER: 6,
          SELECT: false,
          INPUT: true,
        },
      ],
      GENERAL_WORK: [
        {
          KEY: 1,
          NAME: "generalWork",
          LABEL: "Miscellaneous Work",
          ORDER: 1,
          SELECT: true,
          INPUT: false,
        },
        {
          KEY: 2,
          NAME: "time",
          LABEL: "Time In Hrs.",
          ORDER: 1,
          SELECT: true,
          INPUT: false,
        },
        {
          KEY: 3,
          NAME: "remark",
          LABEL: "Remark",
          ORDER: 3,
          SELECT: false,
          INPUT: true,
        },
      ],
    },
    EMPLOYEEE_MASTER: {
      SECTIONS: {
        SECTION_1: "EMPLOYEE DETAILS",
        SECTION_2: "BANK DETAILS",
        SECTION_3: "USER DETAILS",
        SECTION_4: "SALARY DETAILS",
      },
      EMPLOYEE_DETAILS: [
        {
          KEY: 1,
          NAME: "employeeID",
          LABEL: "Employee ID",
          ORDER: 1,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 2,
          NAME: "joiningDate",
          LABEL: "Joining Date",
          ORDER: 2,
          SELECT: false,
          INPUT: false,
          DATE: true,
        },
        {
          KEY: 3,
          NAME: "releaseDate",
          LABEL: "Release Date",
          ORDER: 3,
          SELECT: false,
          INPUT: false,
          DATE: true,
        },
      ],
      BANK_DETAILS: [
        {
          KEY: 1,
          NAME: "accountNo",
          LABEL: "Account Number",
          ORDER: 1,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 2,
          NAME: "ifscCode",
          LABEL: "IFSC Code",
          ORDER: 2,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 3,
          NAME: "bankName",
          LABEL: "Bank Name",
          ORDER: 3,
          SELECT: false,
          INPUT: true,
        },
      ],
      USER_DETAILS: [
        {
          KEY: 1,
          NAME: "userName",
          LABEL: "User Name",
          ORDER: 1,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 2,
          NAME: "accessCategory",
          LABEL: "Bank Name",
          ORDER: 2,
          SELECT: true,
          INPUT: false,
        },
      ],
      SALARY_DETAILS: [
        {
          KEY: 1,
          NAME: "date3",
          LABEL: "Date",
          ORDER: 1,
          SELECT: false,
          INPUT: false,
          DATE: true,
        },
        {
          KEY: 2,
          NAME: "designation",
          LABEL: "Designation",
          ORDER: 2,
          SELECT: true,
          INPUT: false,
        },
        {
          KEY: 3,
          NAME: "salaryPerDay",
          LABEL: "SALARY / DAY",
          ORDER: 3,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 4,
          NAME: "designation",
          LABEL: "Designation",
          ORDER: 4,
          SELECT: true,
          INPUT: false,
        },
        {
          KEY: 5,
          NAME: "overtimeRatio",
          LABEL: "Overtime Ratio",
          ORDER: 5,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 6,
          NAME: "earningRatio",
          LABEL: "Earning Ratio",
          ORDER: 6,
          SELECT: false,
          INPUT: true,
        },
        {
          KEY: 7,
          NAME: "incentiveRatio",
          LABEL: "Incentive Ratio",
          ORDER: 7,
          SELECT: false,
          INPUT: true,
        },
      ],
    },
    COMPANY_INFORMATION: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Name",
        NAME: "name",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Address",
        NAME: "address",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Pin_Code",
        NAME: "pinCode",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "State",
        NAME: "state",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Contry",
        NAME: "contry",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Mobile_No",
        NAME: "mobileNo",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "EMAIL",
        NAME: "email",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    ACCOUNT_MASTER_FORM: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Account_Name",
        NAME: "accountName",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Address",
        NAME: "address",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    EMPLOYEE_MASTER: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Emp_ID",
        NAME: "empID",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Joining_Date",
        NAME: "joiningDate",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Release_Date",
        NAME: "releaseDate",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "First_Name",
        NAME: "firstName",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Maiden_Name",
        NAME: "maidenName",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Surname",
        NAME: "surname",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Gender",
        NAME: "gender",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 9,
        LABEL: "DOB",
        NAME: "dob",
        ORDER: 9,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 10,
        LABEL: "Mobile_No",
        NAME: "mobileNo",
        ORDER: 10,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 11,
        LABEL: "Aadhar_No",
        NAME: "aadharNo",
        ORDER: 11,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 12,
        LABEL: "Address",
        NAME: "address",
        ORDER: 12,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 13,
        LABEL: "Account_No",
        NAME: "accountNo",
        ORDER: 13,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 14,
        LABEL: "IFSC_Code",
        NAME: "ifscCode",
        ORDER: 14,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 15,
        LABEL: "Bank_Name",
        NAME: "bankName",
        ORDER: 15,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    USER_DETAILS: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Emp_ID",
        NAME: "empID",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "User_Name",
        NAME: "userName",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Password",
        NAME: "password",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Access_Category",
        NAME: "accessCategory",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    SALARY_DETAILS: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Emp_ID",
        NAME: "empID",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Date",
        NAME: "date",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Designation",
        NAME: "designation",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Salary_Per_Day",
        NAME: "salaryPerDay",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Overtime_Ratio",
        NAME: "overtimeRatio",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Earning_Ratio",
        NAME: "earningRatio",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Incentive_Ratio",
        NAME: "incentiveRatio",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    ITEM_MASTER: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Drg_No",
        NAME: "drgNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Desc",
        NAME: "desc",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Size",
        NAME: "size",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Item_Group",
        NAME: "itemGroup",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Mat_Hand_Charg",
        NAME: "materialHandCharges",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Rh_Wt",
        NAME: "rhWt",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Fi_Wt",
        NAME: "fiWt",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 9,
        LABEL: "UOM",
        NAME: "uom",
        ORDER: 9,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    OPERATION_DETAILS: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Drg_No",
        NAME: "drgNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Opn_No",
        NAME: "opnNo",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Opn",
        NAME: "opn",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Opn_Desc",
        NAME: "opnDesc",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Opn_Details",
        NAME: "opnDetails",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Time_Min",
        NAME: "timeMin",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Cost",
        NAME: "cost",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    OPERATION_MASTER: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Opn_Name",
        NAME: "opnName",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Per_Hrs_Rate",
        NAME: "perHrsRate",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    OPERATION_DESCRIPTION: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Opn_Name",
        NAME: "opnName",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Sr_No",
        NAME: "srNo",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Opn_Desc",
        NAME: "opnDesc",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    MACHINE_MASTER: {
      SECTIONS: {
        SECTION_1: "Machine Master Details",
        // SECTION_2: "Work Hours",
        // SECTION_3: "Work Details",
      },
      INPUT_DATA: [
        {
          KEY: 1,
          LABEL: "ID",
          NAME: "id",
          ORDER: 1,
          SELECT: true,
          INPUT: false,
          DATE: false,
        },
        {
          KEY: 2,
          LABEL: "Sr_No",
          NAME: "srNo",
          ORDER: 2,
          SELECT: true,
          INPUT: false,
          DATE: false,
        },
        {
          KEY: 3,
          LABEL: "Machine_Name",
          NAME: "machineName",
          ORDER: 3,
          SELECT: true,
          INPUT: false,
          DATE: false,
        },
        {
          KEY: 4,
          LABEL: "Macine_Specification",
          NAME: "macineSpecification",
          ORDER: 4,
          SELECT: true,
          INPUT: false,
          DATE: false,
        },
        {
          KEY: 5,
          LABEL: "Operation",
          NAME: "operation",
          ORDER: 5,
          SELECT: true,
          INPUT: false,
          DATE: false,
        },
        {
          KEY: 6,
          LABEL: "Machine_Per_Hrs_Rate",
          NAME: "machinePerHrsRate",
          ORDER: 6,
          SELECT: true,
          INPUT: false,
          DATE: false,
        },
      ],
    },
    GENRAL_WORK_LIST: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Sr_No",
        NAME: "srNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Genral_Work",
        NAME: "genralWork",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    WORK_ORDER: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Order_No",
        NAME: "orderNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Date",
        NAME: "date",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Customer",
        NAME: "customer",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    WORK_ORDER_DETAILS: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Order_No",
        NAME: "orderNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Sr_No",
        NAME: "srNo",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "PO_Ref",
        NAME: "poRef",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Drg_No",
        NAME: "drgNo",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Qty",
        NAME: "qty",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Rate",
        NAME: "rate",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Work_Details",
        NAME: "workDetails",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 9,
        LABEL: "Remark",
        NAME: "remark",
        ORDER: 9,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 10,
        LABEL: "Prod_Qty",
        NAME: "prodQty",
        ORDER: 10,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 11,
        LABEL: "Out_Qty",
        NAME: "outQty",
        ORDER: 11,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 12,
        LABEL: "Bal_Qty",
        NAME: "balQty",
        ORDER: 12,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 13,
        LABEL: "Rej_Qty",
        NAME: "rejQty",
        ORDER: 13,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    WORK_ORDER_OPERATION_WISE_SPLIT_UP: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Order_No",
        NAME: "orderNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Sr_No",
        NAME: "srNo",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Drg_No",
        NAME: "drgNo",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Opn_No",
        NAME: "opnNo",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Qty",
        NAME: "qty",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Prod_Qty",
        NAME: "prodQty",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Job_Out_Qty",
        NAME: "jobOutQty",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 9,
        LABEL: "Job_In_Qty",
        NAME: "jobInQty",
        ORDER: 9,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 10,
        LABEL: "Bal_Qty",
        NAME: "balQty",
        ORDER: 10,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 11,
        LABEL: "Rej_Qty",
        NAME: "rejQty",
        ORDER: 11,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    SALE_CHALLAN: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Challan_No",
        NAME: "Challan_No",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "DATE",
        NAME: "date",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "NAME",
        NAME: "name",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    SALE_CHALLAN_DETAILS: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "CH_NO",
        NAME: "chNO",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Ch_Sr_No",
        NAME: "chSrNo",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "WO_No",
        NAME: "woNo",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "WO_Sr_No",
        NAME: "woSrNo",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "PO_Ref",
        NAME: "poRef",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Drg_No",
        NAME: "drgNo",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Qty",
        NAME: "qty",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 9,
        LABEL: "Rate",
        NAME: "rate",
        ORDER: 9,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 10,
        LABEL: "Remark",
        NAME: "remark",
        ORDER: 10,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    DAILY_WORK_REPORT: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Report_No",
        NAME: "reportNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Date",
        NAME: "date",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Worker_No",
        NAME: "workerNo",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Check_In",
        NAME: "checkIn",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Check_Out",
        NAME: "checkOut",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Approval",
        NAME: "approval",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    EARNING_DETAILS: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Report_No",
        NAME: "reportNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Sr_No",
        NAME: "srNo",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Macine_No",
        NAME: "macineNo",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Drawing_No",
        NAME: "drawingNo",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Order_No",
        NAME: "orderNo",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Order_Sr_No",
        NAME: "orderSrNo",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Opn",
        NAME: "opn",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 9,
        LABEL: "Opn_Details",
        NAME: "opnDetails",
        ORDER: 9,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 10,
        LABEL: "Qty",
        NAME: "qty",
        ORDER: 10,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 11,
        LABEL: "Time",
        NAME: "time",
        ORDER: 11,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 12,
        LABEL: "Earning_Cost",
        NAME: "earningCost",
        ORDER: 12,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    GENRAL_WORK_DETAILS: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Report_No",
        NAME: "reportNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Sr_No",
        NAME: "srNo",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Misc_Work",
        NAME: "miscWork",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Hrs",
        NAME: "hrs",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Remark",
        NAME: "remark",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    JOB_WORK_ORDER: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "JWO_No",
        NAME: "jwoNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Date",
        NAME: "date",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Vendor_Name",
        NAME: "vendorName",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    JOB_WORK_ORDER_DETAILS: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "JWO_No",
        NAME: "jwoNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "JWO_Sr_No",
        NAME: "jwo_Sr_No",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Drg_No",
        NAME: "drgNo",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Qty",
        NAME: "qty",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Del_Date",
        NAME: "delDate",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Work_Details",
        NAME: "workDetails",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Rate",
        NAME: "rate",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 9,
        LABEL: "Total_Cost",
        NAME: "totalCost",
        ORDER: 9,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 10,
        LABEL: "JWO_In_Qty",
        NAME: "jwo_In_Qty",
        ORDER: 10,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 11,
        LABEL: "Bal_Qty",
        NAME: "balQty",
        ORDER: 11,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 12,
        LABEL: "Rej_Qty",
        NAME: "rejQty",
        ORDER: 12,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    JOB_WORK_ORDER_OPERATION_WISE_SPLIT_UP: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "JWO_No",
        NAME: "jwoNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "JWO_Sr_No",
        NAME: "jwoSrNo",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Drg_No",
        NAME: "drgNo",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Opn_No",
        NAME: "opnNo",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "jobOutQty",
        NAME: "#REF!",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Job_In_Qty",
        NAME: "jobInQty",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Bal_Qty",
        NAME: "balQty",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 9,
        LABEL: "Rej_Qty",
        NAME: "rejQty",
        ORDER: 9,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    JOB_WORK_RECEIPT: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Inword_No",
        NAME: "inwordNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Date",
        NAME: "date",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Name",
        NAME: "name",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    JOB_WORK_RECEIPT_DETAILS: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Inword_No",
        NAME: "inwordNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Sr_No",
        NAME: "srNo",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Ref_JWO_No",
        NAME: "refJWONo",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Drg_No",
        NAME: "drgNo",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Work_Details",
        NAME: "workDetails",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Qty",
        NAME: "qty",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Rate",
        NAME: "rate",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 9,
        LABEL: "Total_Cost",
        NAME: "totalCost",
        ORDER: 9,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 10,
        LABEL: "Remark",
        NAME: "remark",
        ORDER: 10,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    REJECTION_REPORT: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Report_No",
        NAME: "reportNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Date",
        NAME: "date",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Name",
        NAME: "name",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
    REJECTION_REPORT_DETAILS: [
      {
        KEY: 1,
        LABEL: "ID",
        NAME: "id",
        ORDER: 1,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 2,
        LABEL: "Report_No",
        NAME: "reportNo",
        ORDER: 2,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 3,
        LABEL: "Sr_No",
        NAME: "srNo",
        ORDER: 3,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 4,
        LABEL: "Work_Order_No",
        NAME: "workOrderNo",
        ORDER: 4,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 5,
        LABEL: "Drawing_No",
        NAME: "drawingNo",
        ORDER: 5,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 6,
        LABEL: "Opn_Details",
        NAME: "opnDetails",
        ORDER: 6,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 7,
        LABEL: "Qty",
        NAME: "qty",
        ORDER: 7,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 8,
        LABEL: "Mat_Cost",
        NAME: "matCost",
        ORDER: 8,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
      {
        KEY: 9,
        LABEL: "Rej_Details",
        NAME: "rejDetails",
        ORDER: 9,
        SELECT: true,
        INPUT: false,
        DATE: false,
      },
    ],
  },
};